# API_KEY.py
# https://platform.lingyiwanwu.com
YI_KEY = "YOUR_YI_KEY_HERE"
QIANFAN_ACCESS_KEY = "YOUR_QIANFAN_ACCESS_KEY"
QIANFAN_SECRET_KEY = "YOUR_QIANFAN_SECRET_KEY"
APPBUILDER_TOKEN = "YOUR_APPBUILDER_TOKEN"
